### ISSUE TITLE
Got default backend - 404 when request http(s)://mydomain/something

### ISSUE THREAD

**Issue by adrienbarreau** [jetstack/kube-lego#115]
http(s)://mydomain.com/ works great, but every request like http(s)://mydomain.com/something return **default backend - 404**

The firewall looks ok though.
![capture d ecran 2017-03-23 a 17 39 50](https://cloud.githubusercontent.com/assets/5724782/24261244/a3fbcab0-0ff6-11e7-98c1-9a95df796c52.png)

Any lead ?

**Comment by gianrubio** [comment]
This issue is more related to kubernetes/ingress than kube-lego. Please share your configmaps and ingress configs.

**Comment by romdim** [comment]
I have the same issue at #98 

configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-lego
  namespace: kube-lego
data:
  lego.email: "email@email.com"
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
```

ingress-tls:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: staging-web-app
  namespace: staging
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - dns.com
    secretName: staging-web-app-tls
  rules:
  - host: dns.com
    http:
      paths:
      - path: /
        backend:
          serviceName: staging-web-app
          servicePort: 80
```

and for what it's worth, service:
```
apiVersion: v1
kind: Service
metadata:
  name: staging-web-app
  namespace: staging
  labels:
    app: staging-web-app
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
  selector:
    app: staging-web-app
```

Please do advise! Thanks a lot!

**Comment by adrienbarreau** [comment]
configmap:


```yaml
apiVersion: v1
metadata:
  name: kube-lego
  namespace: kube-lego
data:
  lego.email: "email@gmail.com"
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
kind: ConfigMap
```

ingress-tls
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mydomain
  namespace: mydomain
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - messenger.mydomain.com
    secretName: mydomain-tls
  rules:
  - host: messenger.mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: mydomain
          servicePort: 80
```

**Comment by gianrubio** [comment]
@romdim @adrienbarreau I'm not used to gce, but let's try help you.

Both of you has the path ```/*``` before ```/.well-know/...``` path. What happens if you change the order in your ingress? 

If isn't fix, change ```- path: /``` to ```- path: /fake``` and restart kube-lego

Take a look in the screenshot of gce instructions, the order is different 

![gce](https://raw.githubusercontent.com/jetstack/kube-lego/master/examples/gce/gce-lbc.png)

**Comment by romdim** [comment]
I've already tried that unfortunately as described in #98 
If I change the path to match the one in the image it works for a few minutes and after that it is changed back automatically somehow.

I'll try the second solution you're suggesting now!

**Comment by gianrubio** [comment]
I just reproduce this issue now. 

If I change the ingress path from ```/``` to ```/bla```, kube-lego generate the right certificate.

I'm working now to fix this

**Comment by romdim** [comment]
Ok, cool, because second solution didn't work as well..
Only temporary solution is to change /* order, but not for long..

**Comment by gianrubio** [comment]
What happened to me?

1. I deployed the same gce examples. 
2.  In the beginning I got 404 errors
3. got 502 error
4. After ~= 1 min kube-lego pass the selftest and my certificate was created.

@romdim how long did you wait after you've created the resources?  

Could you change the kube-lego deployment to show verbose logs and post the full kube-lego logs.

```
       - name: LEGO_LOG_LEVEL
          value: debug
```

**My Logs**
```
[kube-lego-937511810-w9jkw] time="2017-03-29T17:23:34Z" level=info msg="no cert associated with ingress" context="ingress_tls" name=echoserver namespace=echoserver
[kube-lego-937511810-w9jkw] time="2017-03-29T17:23:34Z" level=info msg="requesting certificate for grubio.my.domain" context="ingress_tls" name=echoserver namespace=echoserver
[kube-lego-937511810-w9jkw] time="2017-03-29T17:23:34Z" level=debug msg="testing reachablity of http://grubio.my.domain/.well-known/acme-challenge/_selftest" context=acme domain=grubio.my.domain
[kube-lego-937511810-w9jkw] time="2017-03-29T17:23:34Z" level=debug msg="error while authorizing: reachabily test failed: wrong status code '502'" context=acme domain=grubio.my.domain
[kube-lego-937511810-w9jkw] time="2017-03-29T17:23:34Z" level=debug msg="testing reachablity of http://grubio.my.domain/.well-known/acme-challenge/_selftest" context=acme domain=grubio.my.domain
[kube-lego-937511810-w9jkw] time="2017-03-29T17:23:34Z" level=debug msg="error while authorizing: reachabily test failed: wrong status code '502'" context=acme domain=grubio.my.domain
[kube-lego-937511810-w9jkw] time="2017-03-29T17:23:35Z" level=debug msg="testing reachablity of http://grubio.my.domain/.well-known/acme-challenge/_selftest" context=acme domain=grubio.my.domain
[kube-lego-937511810-w9jkw] time="2017-03-29T17:23:35Z" level=debug msg="error while authorizing: reachabily test failed: wrong status code '502'" context=acme domain=grubio.my.domain
[kube-lego-937511810-w9jkw] time="2017-03-29T17:24:34Z" level=debug msg="setting up svc endpoint" context=provider namespace=echoserver pod_ip=10.0.1.8 provider=gce
[kube-lego-937511810-w9jkw] time="2017-03-29T17:24:34Z" level=info msg="process certificates requests for ingresses" context=kubelego
[kube-lego-937511810-w9jkw] time="2017-03-29T17:24:34Z" level=info msg="creating new secret" context=secret name=echoserver-tls namespace=echoserver
[kube-lego-937511810-w9jkw] time="2017-03-29T17:24:34Z" level=info msg="no cert associated with ingress" context="ingress_tls" name=echoserver namespace=echoserver
[kube-lego-937511810-w9jkw] time="2017-03-29T17:24:34Z" level=info msg="requesting certificate for grubio.my.domain" context="ingress_tls" name=echoserver namespace=echoserver
```

**Comment by romdim** [comment]
@gianrubio 
I remember that it had worked for me after some minutes, I can't recall how many as it was 15 days ago as you can see from the logs:

```
2017-03-29T17:46:49.536310269Z time="2017-03-29T17:46:49Z" level=info msg="kube-lego 0.1.3-d425b293 starting" context=kubelego 
2017-03-29T17:46:49.645892279Z time="2017-03-29T17:46:49Z" level=info msg="connected to kubernetes api v1.5.3" context=kubelego 
2017-03-29T17:46:49.645924371Z time="2017-03-29T17:46:49Z" level=debug msg="start watching ingress objects" context=kubelego 
2017-03-29T17:46:49.646078325Z time="2017-03-29T17:46:49Z" level=info msg="server listening on http://:8080/" context=acme 
2017-03-29T17:46:49.671528190Z time="2017-03-29T17:46:49Z" level=debug msg="CREATE ingress/staging/staging-web-app" context=kubelego 
2017-03-29T17:46:49.671571056Z time="2017-03-29T17:46:49Z" level=debug msg="worker: begin processing true" context=kubelego 
2017-03-29T17:46:49.684631133Z time="2017-03-29T17:46:49Z" level=debug msg=reset context=provider provider=gce 
2017-03-29T17:46:49.690965546Z time="2017-03-29T17:46:49Z" level=debug msg=finialize context=provider provider=gce 
2017-03-29T17:46:49.693880564Z time="2017-03-29T17:46:49Z" level=debug msg="setting up svc endpoint" context=provider namespace=staging pod_ip=10.4.0.215 provider=gce 
2017-03-29T17:46:49.710254784Z time="2017-03-29T17:46:49Z" level=debug msg=reset context=provider provider=nginx 
2017-03-29T17:46:49.710284007Z time="2017-03-29T17:46:49Z" level=debug msg=finialize context=provider provider=nginx 
2017-03-29T17:46:49.714336514Z time="2017-03-29T17:46:49Z" level=info msg="disable provider no TLS hosts found" context=provider provider=nginx 
2017-03-29T17:46:49.714456954Z time="2017-03-29T17:46:49Z" level=info msg="process certificates requests for ingresses" context=kubelego 
2017-03-29T17:46:49.720441344Z time="2017-03-29T17:46:49Z" level=info msg="cert expires in 75.0 days, no renewal needed" context="ingress_tls" expire_time=2017-06-12 16:39:00 +0000 UTC name=staging-web-app namespace=staging 
2017-03-29T17:46:49.721275029Z time="2017-03-29T17:46:49Z" level=info msg="no cert request needed" context="ingress_tls" name=staging-web-app namespace=staging 
2017-03-29T17:46:49.721353014Z time="2017-03-29T17:46:49Z" level=debug msg="worker: done processing true" context=kubelego 
```

**Comment by ianmartorell** [comment]
I have the same issue, modifying the paths in the load balancer settings fixes it, but it reverts after a few minutes. My logs look like this:

```
time="2017-03-29T13:17:59Z" level=info msg="requesting certificate for XXXX.com" context="ingress_tls" name=panel namespace=staging
time="2017-03-29T13:19:25Z" level=warning msg="authorization failed after 1m0s: reachabily test failed: wrong status code '502'" context=acme domain=XXXX.com
time="2017-03-29T13:19:25Z" level=error msg="Error while process certificate requests: no domain could be authorized successfully" context=kubelego
time="2017-03-29T13:19:26Z" level=info msg="disable provider no TLS hosts found" context=provider provider=nginx
time="2017-03-29T13:19:26Z" level=info msg="process certificates requests for ingresses" context=kubelego
time="2017-03-29T13:19:26Z" level=info msg="creating new secret" context=secret name=panel-tls namespace=staging
time="2017-03-29T13:19:26Z" level=info msg="no cert associated with ingress" context="ingress_tls" name=panel namespace=staging
time="2017-03-29T13:19:26Z" level=info msg="requesting certificate for XXXX.com" context="ingress_tls" name=panel namespace=staging
time="2017-03-29T13:20:26Z" level=info msg="authorization successful" context=acme domain=XXXX.com
time="2017-03-29T13:20:27Z" level=info msg="successfully got certificate: domains=[XXXX.com] url=https://acme-v01.api.letsencrypt.org/acme/cert/03fc8e21d99ff1b9d85117087a2516bd0486" context=acme
time="2017-03-29T13:20:27Z" level=info msg="creating new secret" context=secret name=panel-tls namespace=staging
time="2017-03-29T13:24:04Z" level=info msg="disable provider no TLS hosts found" context=provider provider=nginx
time="2017-03-29T13:24:04Z" level=info msg="process certificates requests for ingresses" context=kubelego
time="2017-03-29T13:24:04Z" level=info msg="cert expires in 90.0 days, no renewal needed" context="ingress_tls" expire_time=2017-06-27 12:20:00 +0000 UTC name=panel namespace=staging
time="2017-03-29T13:24:04Z" level=info msg="no cert request needed" context="ingress_tls" name=panel namespace=staging
time="2017-03-29T19:32:29Z" level=info msg="Periodically check certificates at 2017-03-29 19:32:29.427463704 +0000 UTC" context=kubelego
time="2017-03-29T19:32:29Z" level=info msg="disable provider no TLS hosts found" context=provider provider=nginx
time="2017-03-29T19:32:29Z" level=info msg="process certificates requests for ingresses" context=kubelego
time="2017-03-29T19:32:29Z" level=info msg="cert expires in 89.7 days, no renewal needed" context="ingress_tls" expire_time=2017-06-27 12:20:00 +0000 UTC name=panel namespace=staging
time="2017-03-29T19:32:29Z" level=info msg="no cert request needed" context="ingress_tls" name=panel namespace=staging
```

**Comment by ianmartorell** [comment]
It seems we can keep the paths in the load balancer like we want them by changing `/` to `/*` in the Ingress yaml.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: XXXXX
  namespace: staging
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - XXXXX.com
    secretName: XXXXX-tls
  rules:
  - host: XXXXX.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: XXXXX
          servicePort: 80
```

**Comment by romdim** [comment]
It was so obvious!!!
Have been going around this for a month and hadn't seen it.. Thank you so much @ianmartorell!

**Comment by gianrubio** [comment]
@ianmartorell are you able to do a PR in the docs? All the other user can avoid this issue :)

**Comment by ianmartorell** [comment]
Done!

**Comment by camilb** [comment]
This configuration works well for me.

    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: mysite
      namespace: default
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "gce"
    spec:
      tls:
      - hosts:
        - www.mysite.com
        secretName: mysite-tls
      backend:
        serviceName: ghost
        servicePort: 80
      rules:
      - host: www.mysite.com
        http:
          paths:
          - path: /*
            backend:
              serviceName: ghost
              servicePort: 80
      - host: www.mysite.com
        http:
          paths:
          - path: /.well-known/acme-challenge
            backend:
              serviceName: kube-lego-gce
              servicePort: 8080

**Comment by Mykolaichenko** [comment]
I've tried a lot of, but @ianmartorell example works well. 
In my case problem was in yaml: 
there is my manifest: 
```
  tls:
  - secretName: XXX-tls
    hosts:
    - XXX.com
```
from GCE docs and examples, but i's generate `default backend 404` error. 

But following syntax working pretty well: 
```
spec:
  tls:
  - hosts:
    - XXXXX.com
    secretName: XXXXX-tls
```
Hope it helps!
