### ISSUE TITLE
No Services, no Secretes created, just kind of sits there

### ISSUE THREAD

**Issue by chepurko** [jetstack/kube-lego#128]
According to the docs, starting the kube-lego Deployment should be followed with automatic Service and Secret creations of some sort. Apparently that's not working for me. If I try to deploy the TLS Ingress after bringing up kube-lego:
```bash
$ kubectl apply -f wp-bc/tls-Ingress.yaml 
error: yaml: line 13: did not find expected key
```
Which is saying that it can't find a Secret with the given name.

My logs are thus with ` LEGO_LOG_LEVEL=debug`:
```bash
2017-03-26T23:37:35.123622100Z time="2017-03-26T23:37:35Z" level=info msg="kube-lego 0.1.3-d425b293 starting" context=kubelego 
2017-03-26T23:37:35.156631213Z time="2017-03-26T23:37:35Z" level=info msg="connected to kubernetes api v1.5.5" context=kubelego 
2017-03-26T23:37:35.156755548Z time="2017-03-26T23:37:35Z" level=debug msg="start watching ingress objects" context=kubelego 
2017-03-26T23:37:35.156883611Z time="2017-03-26T23:37:35Z" level=info msg="server listening on http://:8080/" context=acme
```

I followed the [NGINX example](https://github.com/jetstack/kube-lego/tree/master/examples/nginx) and I also used those YAMLs in the same format. I did condense the file count by putting some of them together. I really doubt this would be a problem though...

Thanks.

**Comment by ankon** [comment]
Can you post your yaml files (ingress + manifests for kube-lego) nonetheless? There might be a clue in them about what is going on.

**Comment by chepurko** [comment]
Sure, I was going to run through your NGINX example plain-vanilla on my cluster just to see it working without any of my modifications. I'm thinking whether my labels/selectors/namespaces have anything to do with kube-lego just hanging out.

```yaml
# 00-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: wp-echo
```
```yaml
# notls-Ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wp-echo
  namespace: wp-echo
  annotations:
    # kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  # tls:
  # - hosts:
  #   - www.echoserver.com
  #   secretName: wp-echo-tls
  rules:
  - host: www.echoserver.com
    http:
      paths:
      - path: /
        backend:
          serviceName: wp-echo
          servicePort: 80
```
```yaml
# tls-Ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wp-echo
  namespace: wp-echo
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
   tls:
   - hosts:
     - www.echoserver.com
     secretName: wp-echo-tls
  rules:
  - host: www.echoserver.com
    http:
      paths:
      - path: /
        backend:
          serviceName: wp-echo
          servicePort: 80
```
```yaml
# wp-echo-Deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: wp-echo
  namespace: wp-echo
  labels:
    app: wp-echo
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: wp-echo
    tier: frontend
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-echo-pv-claim
  namespace: wp-echo
  labels:
    app: wp-echo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: wp-echo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp-echo
  namespace: wp-echo
  labels:
    app: wp-echo
    tier: frontend
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: wp-nginx
        app: wp-echo
        tier: frontend
    spec:
      containers:
      - image: chepurko/wordpress-fpm-redis:v1.0
        name: wp-fpm
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb.core.svc.cluster.local # this must be the FQDN of the mariadb Service
        - name: WORDPRESS_DB_NAME
          value: dbWPECHO
        - name: WORDPRESS_DB_USER
          value: wp-echo
        - name: WORDPRESS_DB_PASSWORD
          value: PASSWORDECHO
        #ports:
        #- containerPort: 9000
        #  name: php
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
      - image: chepurko/nginx-fpm
        name: nginx-fpm
        env:
        - name: BEHIND_PROXY
          value: "true"
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wp-persistent-storage
        persistentVolumeClaim:
          claimName: wp-echo-pv-claim
```
```yaml
# 00-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kube-lego
```
```yaml
# kube-lego-Deployment.yaml
apiVersion: v1
metadata:
  name: kube-lego
  namespace: kube-lego
data:
  # modify this to specify your address
  lego.email: "admin@echoserver.com"
  # configure letencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
kind: ConfigMap
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-lego
  namespace: kube-lego
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-lego
    spec:
      containers:
      - name: kube-lego
        image: jetstack/kube-lego:0.1.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: LEGO_EMAIL
          valueFrom:
            configMapKeyRef:
              name: kube-lego
              key: lego.email
        - name: LEGO_URL
          valueFrom:
            configMapKeyRef:
              name: kube-lego
              key: lego.url
        - name: LEGO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LEGO_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: LEGO_LOG_LEVEL
          value: debug
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
```
```yaml
# nginx-Deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-ingress
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: nginx
    tier: ingress
---
apiVersion: v1
data:
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-timeout: "600"
  hsts-include-subdomains: "false"
  proxy-body-size: "64m"
  server-name-hash-bucket-size: "256"
kind: ConfigMap
metadata:
  namespace: nginx-ingress
  name: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-ingress
  labels:
    app: nginx
    tier: ingress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        tier: ingress
    spec:
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.3
        name: nginx
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 80
        - containerPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=nginx-ingress/default-http-backend
        - --configmap=nginx-ingress/nginx
```
