### ISSUE TITLE
404 issue with GCE example

### ISSUE THREAD

**Issue by devth** [jetstack/kube-lego#15]
I followed the GCE example but continually see logs like this in the kube-lego pod:

```
time="2016-08-14T16:50:19Z" level=debug msg="testing reachablity of http://foo.redacted.com/.well-known/acme-challenge/_selftest" context=acme host=foo.redacted.com
time="2016-08-14T16:50:19Z" level=warning msg="wrong status code '404'" context=acme host=foo.redacted.com
```

My DNS record is pointed at the Ingress external IP for `foo.redcated.com`. I can curl it via http, but only the html index is accessible: all of its css js and images 404.

Are there any suggested debugging steps? I previously had this working but wanted to try out the GCE solution.

**Edit**: I also see a bunch of `wrong status code '502'` logs after killing the kube-lego pod and watching the new one come up.

**Edit 2**: looks like the css/js/images issue was fixed by updating `      - path: /` to `      - path: /*` in my ingress object.

**Comment by simonswine** [comment]
The GCE has probably still a few problems, can you provide me with this:

- ingress yaml
- kubectl describe of the ingress 
- a screenshot of the forwarding rule in gce console

**Comment by devth** [comment]
Ingress

```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - secretName: foo-tls
    hosts:
    - foo.redacted.com
  rules:
  - host: foo.redacted.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: foo
          servicePort: 80
```

kubectl describe

```
Name:			foo
Namespace:		default
Address:		130.x.x.x
Default backend:	default-http-backend:80 (10.0.1.3:8080)
TLS:
  foo-tls terminates foo.redacted.com
Rules:
  Host			Path	Backends
  ----			----	--------
  foo.redacted.com	
    			/* 	foo:80 (<none>)
Annotations:
  backends:		{"k8s-be-30314--c2cd235f2196d4d5":"HEALTHY","k8s-be-31354--c2cd235f2196d4d5":"HEALTHY"}
  forwarding-rule:	k8s-fw-default-foo--c2cd235f2196d4d5
  target-proxy:		k8s-tp-default-foo--c2cd235f2196d4d5
  url-map:		k8s-um-default-foo--c2cd235f2196d4d5
No events.
```

![image](https://cloud.githubusercontent.com/assets/86107/17670912/6f4c37b4-62d1-11e6-8268-4dd60c7a9a99.png)
