### ISSUE TITLE
support for getting hosts lists from configMaps

### ISSUE THREAD

**Issue by nergdron** [jetstack/kube-lego#150]
I've got all of my apps' configs in configmaps, but when I try to do something like this, it fails with a syntax error:

```
spec:
  tls:
  - secretName: appname-tls
    hosts:
      - valueFrom:
          configMapKeyRef:
            name: appname
            key: LOCAL_DOMAIN
```

It'd be super useful to be able to generate the hosts list from configMap entries so we're not having to hardcode these values.
