### ISSUE TITLE
Ignore an existing secret with a certificate

### ISSUE THREAD

**Issue by stibi** [jetstack/kube-lego#151]
Hello,

I have this use case: 

- multiple, usualy 2 host rules per ingress, 2 tls host rules
- the first host got a wildcard certificate I have stored in a secret
- the second host should be issued with a certificate from LetsEncrypt using kube-lego

Now, how to keep kube-lego away from the secret with the wildcard certificate? :)

Once I setup the tls-acme annotation, the secret is replaced with an LE certificate and other sites using the wildcard certificate got a trouble…

I have encoutered this problem just recently, weird is that it works this way on another cluster…but as I'm looking into logs, maybe it works just by accident, becuase:

```
time="2017-04-20T11:04:27Z" level=warning msg="the secret wild-certificate/hosting is used multiple times. These linked TLS ingress elements where ignored: ingress hosting/hosting-3zwh85uz (hosts: 3zwh85uz.foo.bar), ingress hosting/hosting-f7gwfoxg (hosts: f7gwfoxg.foo.bar), ingress hosting/hosting-mijcf5kj (hosts: mijcf5kj.foo.bar)" context=kubelego
```

Any opinions, please? Am I doing it wrong? If it sounds like a valid case, I'm ready to get coding :)

Thanks!

**Comment by gianrubio** [comment]
@stibi what about to split your ingress in 2 resources?

1-  Put your wildcard certificate without ```kubernetes.io/tls-acme``` annotation. 
2- Create another ingress with your certs and annotate with ```kubernetes.io/tls-acme: "true"```

```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: wildcard
  spec:
    rules:

....

- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:  
      kubernetes.io/tls-acme: "true"
    name: no-wildcard
  spec:
    rules:
....
```
