### ISSUE TITLE
deployment.yaml: "don't forget to configure LEGO_POD_IP"

### ISSUE THREAD

**Issue by ahmetb** [jetstack/kube-lego#159]
README.md says `don't forget to configure LEGO_POD_IP`. However it's impossible to configure it as it's already using the downward API without any edits to the file:

```
        - name: LEGO_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
```

So there's no configuration required by someone who's trying to install this. The README is confusing about this.
