### ISSUE TITLE
[Question] implications of stopping non-TLS frontend on GCE ingress

### ISSUE THREAD

**Issue by ahmetb** [jetstack/kube-lego#164]
Hi, sorry for opening a lot of issues lately. This time I have a question. Let's say I set up `kube-lego` successfully and it works (currently I'm able to succeed only in LE-staging for some reason #160).

Now I probably want to disable non-TLS (HTTP) traffic. What should I do? Is there something I need to adjust on the `ingress` resource? Or should I just go to Google Cloud Platform Console and remove the HTTP frontend manually?

> ![image](https://cloud.githubusercontent.com/assets/159209/25294982/7d95ca0e-2696-11e7-9413-894940064c3b.png)

What are the implications of this? As far as I can tell, non-TLS (HTTP) endpoint is used to request/refresh certificates. If I disable this, it probably means that I can't refresh certificates.

What your the guidance to run a HTTPs-only service on GKE with kube-lego?

**Comment by MaxDaten** [comment]
Hi,

there is an annotation for the ingress resource, called `kubernetes.io/ingress.allow-http`.

For example:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress
 namespace: default
 annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - example.com
  secretName: tls-secret
  backend:
    serviceName: endpoint
    servicePort: api

```
