### ISSUE TITLE
Do not create services static 

### ISSUE THREAD

**Issue by simonswine** [jetstack/kube-lego#169]
Kube-Lego currently creates all it's required services. We should no longer do that.

The only valid dynamic service creation is for multi-namespace watches on GCE. We should create the static services using helm/charts

**Comment by xeor** [comment]
I have been debugging why my kube-lego setup didn't work. It turned out that kube-lego didn't create the required service automatic (as it sais it should).

I'm using rbac with the rule from https://github.com/kubernetes/ingress/issues/575#issuecomment-292781303, including create permission to `service`. There was no errors, nor any services to be seen.

Based on https://github.com/jetstack/kube-lego/blob/master/pkg/service/service.go#L97, I created a service manually, and everything started to work.

I don't see any reason why this service had to be added magically like this. It was confusing to debug. Specially when you are new to kubernetes. Glad to see this issue addressing this!

The service:

```
apiVersion: v1
kind: Service
metadata:
  name: kube-lego-nginx
  namespace: kube-system
  annotations:
    kubelego.AnnotationKubeLegoManaged: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: "TCP"
  selector:
    app: kube-lego
```
