### ISSUE TITLE
Can't request a certificate, error: waiting for authorization failed: acme: identifier authorization failed" c

### ISSUE THREAD

**Issue by jescarri** [jetstack/kube-lego#171]
My setup is as follows:
- Tectonic Cluster
- Nginx Controller v0.8.3
```kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: nginx-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: nginx-ingress-controller
spec:
  selector:
    matchLabels:
      k8s-app: nginx-ingress-controller
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: nginx-ingress-controller
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: nginx-ingress-controller
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          ports:
            - hostPort: 80
              containerPort: 80
              protocol: TCP
            - hostPort: 443
              containerPort: 443
              protocol: TCP
          imagePullPolicy: IfNotPresent
          image: 'gcr.io/google_containers/nginx-ingress-controller:0.8.3'
          args:
            - /nginx-ingress-controller
            - >-
              --default-backend-service=kube-system/nginx-ingress-default-backend
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      nodeSelector:
        external: 'true'
      hostNetwork: true
      securityContext: {}

```

I can reach ingress enpoints, so Ingress is working properly.

This is my Ingress definition:

```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: cafe-ingress
  namespace: test
  selfLink: /apis/extensions/v1beta1/namespaces/test/ingresses/cafe-ingress
  uid: 90d49530-298a-11e7-8f6f-ceb05f3ffd15
  resourceVersion: '3039728'
  generation: 18
  creationTimestamp: '2017-04-25T07:41:17Z'
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
spec:
  tls:
    - hosts:
        - foo.aws.identitylabs.mx
      secretName: test-tls
  rules:
    - host: foo.aws.identitylabs.mx
      http:
        paths:
          - path: /
            backend:
              serviceName: tea-svc
              servicePort: 80
          - path: /coffee
            backend:
              serviceName: coffee-svc
              servicePort: 80
```

kube-lego manifest:

```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  annotations:
  name: kube-lego-kube-lego
  namespace: kube-system
  labels:
    app: kube-lego
    chart: kube-lego-0.1.8
    heritage: Tiller
    release: kube-lego
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-lego
      release: kube-lego
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-lego
        release: kube-lego
    spec:
      containers:
        - name: kube-lego
          image: 'jetstack/kube-lego:canary'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: LEGO_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: LEGO_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: LEGO_EMAIL
              value: jesuscarrillo8@gmail.com
            - name: LEGO_PORT
              value: '8080'
            - name: LEGO_URL
              value: 'https://acme-v01.api.letsencrypt.org/directory'
            - name: LEGO_LOG_LEVEL
              value: debug
            - name: LEGO_SUPPORTED_INGRESS_CLASS
              value: nginx
            - name: LEGO_DEFAULT_INGRESS_CLASS
              value: nginx
          resources: {}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        internal: 'true'
      securityContext: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

```

I can reach  curl  http://foo.aws.identitylabs.mx/.well-known/acme-challenge/_selftest

```
*   Trying 104.156.96.34...
* Connected to foo.aws.identitylabs.mx (104.156.96.34) port 80 (#0)
> GET /.well-known/acme-challenge/_selftest HTTP/1.1
> Host: foo.aws.identitylabs.mx
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.11.3
< Date: Fri, 28 Apr 2017 07:08:35 GMT
< Content-Type: text/plain
< Content-Length: 16
< Connection: keep-alive
< 
* Connection #0 to host foo.aws.identitylabs.mx left intact
````

kube-lego errors:
```
time="2017-04-28T06:36:47Z" level=debug msg=reset context=provider provider=gce
time="2017-04-28T06:36:47Z" level=debug msg=finalize context=provider provider=gce
time="2017-04-28T06:36:47Z" level=debug msg=reset context=provider provider=nginx
time="2017-04-28T06:36:47Z" level=debug msg=finalize context=provider provider=nginx
time="2017-04-28T06:36:47Z" level=info msg="process certificate requests for ingresses" context=kubelego
time="2017-04-28T06:36:47Z" level=info msg="Attempting to create new secret" context=secret name=test-tls namespace=test
time="2017-04-28T06:36:47Z" level=info msg="no cert associated with ingress" context="ingress_tls" name=cafe-ingress namespace=test
time="2017-04-28T06:36:47Z" level=info msg="requesting certificate for foo.aws.identitylabs.mx" context="ingress_tls" name=cafe-ingress namespace=test
time="2017-04-28T06:36:47Z" level=debug msg="testing reachability of http://foo.aws.identitylabs.mx/.well-known/acme-challenge/_selftest" context=acme domain=foo.aws.identitylabs.mx
time="2017-04-28T06:36:53Z" level=debug msg="error while authorizing: waiting for authorization failed: acme: identifier authorization failed" context=acme domain=foo.aws.identitylabs.mx
time="2017-04-28T06:36:54Z" level=debug msg="testing reachability of http://foo.aws.identitylabs.mx/.well-known/acme-challenge/_selftest" context=acme domain=foo.aws.identitylabs.mx
time="2017-04-28T06:36:59Z" level=debug msg="error while authorizing: waiting for authorization failed: acme: identifier authorization failed" context=acme domain=foo.aws.identitylabs.mx
time="2017-04-28T06:37:00Z" level=debug msg="testing reachability of http://foo.aws.identitylabs.mx/.well-known/acme-challenge/_selftest" context=acme domain=foo.aws.identitylabs.mx
time="2017-04-28T06:37:05Z" level=debug msg="error while authorizing: waiting for authorization failed: acme: identifier authorization failed" context=acme domain=foo.aws.identitylabs.mx
time="2017-04-28T06:37:07Z" level=debug msg="testing reachability of http://foo.aws.identitylabs.mx/.well-known/acme-challenge/_selftest" context=acme domain=foo.aws.identitylabs.mx
time="2017-04-28T06:37:13Z" level=debug msg="error while authorizing: waiting for authorization failed: acme: identifier authorization failed" context=acme domain=foo.aws.identitylabs.mx
time="2017-04-28T06:37:15Z" level=debug msg="testing reachability of http://foo.aws.identitylabs.mx/.well-known/acme-challenge/_selftest" context=acme domain=foo.aws.identitylabs.mx
time="2017-04-28T06:37:21Z" level=debug msg="error while authorizing: waiting for authorization failed: acme: identifier authorization failed" context=acme domain=foo.aws.identitylabs.mx
time="2017-04-28T06:37:24Z" level=debug msg="testing reachability of http://foo.aws.identitylabs.mx/.well-known/acme-challenge/_selftest" context=acme domain=foo.aws.identitylabs.mx
````

Any idea whats wrong?

Is is worth mentioning that I can manually request certificates for the same domain for hosts running on the same network using certbot

Thanks!
