### ISSUE TITLE
GKE ingress only have one certificate when multiple are described in the ingress.yml

### ISSUE THREAD

**Issue by iamfreee** [jetstack/kube-lego#178]
Hi,

I am trying to configure multiple certs for sub domains using kube lego and google cloud platform.

I have two services, one for my staging pod and another for my production pod.

My ingress config:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: restaurants-s
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - secretName: staging-restaurants-tls1
    hosts:
    - staging.otrack.info
  - secretName: prod-restaurants-tls1
    hosts:
    - otrack.info
  backend:
    serviceName: srestaurants-s
    servicePort: 80
  rules:
  # Staging
  - host: staging.otrack.info
    http:
      paths:
      - path: /*
        backend:
          serviceName: srestaurants-s
          servicePort: 80
      - path: /.well-known/acme-challenge
        backend:
          serviceName: kube-lego-gce
          servicePort: 8080

  # Production
  - host: otrack.info
    http:
      paths:
      - path: /*
        backend:
          serviceName: restaurants-s
          servicePort: 80
      - path: /.well-known/acme-challenge
        backend:
          serviceName: kube-lego-gce
          servicePort: 8080
```

The sub domain is working fine:
https://staging.otrack.info

But the main domain has the wrong certificate:
https://otrack.info/

My load balancer only shows one certificate, is this normal?
![image](https://cloud.githubusercontent.com/assets/1500881/25764329/301042a6-31df-11e7-9d95-2337878e804a.png)

The secrets have been created with success by kube lego:
![image](https://cloud.githubusercontent.com/assets/1500881/25764475/e61029b8-31df-11e7-913d-4fc9d8429c6f.png)

Any ideas?

Thanks

**Comment by simonswine** [comment]
The GCE Ingress controller that is used for your setup supports only a single certificate: 

You have these options:
- Setup two ingress object (one for staging, one for production). Will need two googe cloud forwarding rules
- Modify your example to use a single certificate:
```
  tls:
  - secretName: restaurants-tls1
    hosts:
    - staging.otrack.info
    - otrack.info
```
