### ISSUE TITLE
Cert not renewed?

### ISSUE THREAD

**Issue by MaxDaten** [jetstack/kube-lego#19]
Maybe it's a misunderstanding on my side but I just activated kube-lego for a gce ingress with a manually preinstalled certificate which expires in 6 days.

This is the ingress configuration:

```yaml
# ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress
 namespace: default
 annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - sub.example.com
    secretName: tls-secret
  backend:
    serviceName: endpoint
    servicePort: api

  rules:
  - host: sub.example.com
    http:
      paths:
      - path: /something
        backend:
          serviceName: some-service
          servicePort: http
```

I set explicitly `LEGO_MINIMUM_VALIDITY` to "720h".

The log of the kube-lego pod is showing this:

```
time="2016-08-22T20:00:15Z" level=info msg="cert expires in 6.6 days, no renewal needed" context="ingress_tls" expire_time=2016-08-29 09:53:00 +0000 UTC name=ingress namespace=default 
```

So did I misunderstood the minimum validity, and if so when is the cert renewed and how can I control the interval?

Greetings
