### ISSUE TITLE
Trailing slash on `lego.url` causes certificates not to be requested.

### ISSUE THREAD

**Issue by EmlynC** [jetstack/kube-lego#219]
I appreciate that a leaving a trailing slash on the `lego.url` may indicate that the user doesn't know how to format their URLs properly, but doing this:

```yaml
...
data:
  lego.email: "emlyn@felix.com"
  lego.url: "https://acme-v01.api.letsencrypt.org/" 
```

In `configmap.yaml`, will cause this error:

```
level=error msg="Error while processing certificate requests: Head : unsupported protocol scheme \"\"" context=kubelego 
```

Could we make kube-lego a little more tolerant of a trailing slash 😄 ?
