### ISSUE TITLE
Unsupported ingress class

### ISSUE THREAD

**Issue by Stono** [jetstack/kube-lego#312]
Hey, 
I use nginx-ingress in a couple of configurations, as such they have a custom `class` of `nginx-internal` and `nginx-external`.

I want to do kube-lego on the external ingress, but I'm getting:

```
time="2018-01-25T20:36:48Z" level=info msg="ignoring as unsupported ingress class 'nginx-external'. Did you you forget to specify LEGO_DEFAULT_INGRESS_CLASS ?" context=ingress name=at-consumer-platform-ingress-external namespace=default
```

My pod is configured with:
```
        env:
        - name: LEGO_SUPPORTED_INGRESS_CLASS
          value: nginx-external
        - name: LEGO_SUPPORTED_INGRESS_PROVIDER
          value: nginx-external
        - name: LEGO_DEFAULT_INGRESS_CLASS
          value: nginx-external
```

So I'm not really sure what else I could do?
Thanks
Karl
