### ISSUE TITLE
Multiple domains for one service

### ISSUE THREAD

**Issue by johnparn** [jetstack/kube-lego#55]
Hi!

This is a question regarding the best way to handle multiple domains for one service using the nginx ingress-controller. Currently I add the new TLS domain names to the ingress and duplicate the rules for each domain. Could this be written in a less verbose manner?

When adding a new domain name to the list a new SAN-cert that will be issued, hence it would make more sense to apply few bulk changes instead small, multiple changes, to minimize the risk of being blocked from making further certificate requests.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mobile-web-ingress
  namespace: production
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - m.domain.org
    - m.domain.com
    - m.domain.net
    secretName: mobile-web-tls
  rules:
  - host: m.domain.org
    http:
      paths:
      - path: /
        backend:
          serviceName: mobile-web-svc
          servicePort: 80
  - host: m.domain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: mobile-web-svc
          servicePort: 80
  - host: m.domain.net
    http:
      paths:
      - path: /
        backend:
          serviceName: mobile-web-svc
          servicePort: 80
```
