### ISSUE TITLE
Unable to Issue Certificate in GCE

### ISSUE THREAD

**Issue by asadowns** [jetstack/kube-lego#88]
I'm unable to issue a certificate following the GCE example. The kube-lego pod log is below with the reachability error at the bottom:
```
time="2017-02-09T23:56:31Z" level=info msg="kube-lego 0.1.3-d425b293 starting" context=kubelego
time="2017-02-09T23:56:31Z" level=info msg="connected to kubernetes api v1.5.2" context=kubelego
time="2017-02-09T23:56:31Z" level=debug msg="start watching ingress objects" context=kubelego
time="2017-02-09T23:56:31Z" level=info msg="server listening on http://:8080/" context=acme
time="2017-02-09T23:58:12Z" level=debug msg="CREATE ingress/default/my-app" context=kubelego
time="2017-02-09T23:58:12Z" level=debug msg="worker: begin processing true" context=kubelego
time="2017-02-09T23:58:12Z" level=debug msg=reset context=provider provider=gce
time="2017-02-09T23:58:12Z" level=debug msg="UPDATE ingress/default/my-app" context=kubelego
time="2017-02-09T23:58:12Z" level=debug msg=finialize context=provider provider=gce
time="2017-02-09T23:58:12Z" level=debug msg="setting up svc endpoint" context=provider namespace=default pod_ip=10.0.3.33 provider=gce
time="2017-02-09T23:58:12Z" level=debug msg=reset context=provider provider=nginx
time="2017-02-09T23:58:12Z" level=debug msg=finialize context=provider provider=nginx
time="2017-02-09T23:58:12Z" level=info msg="disable provider no TLS hosts found" context=provider provider=nginx
time="2017-02-09T23:58:12Z" level=info msg="process certificates requests for ingresses" context=kubelego
time="2017-02-09T23:58:12Z" level=info msg="creating new secret" context=secret name=default-tls namespace=default
time="2017-02-09T23:58:12Z" level=info msg="no cert associated with ingress" context="ingress_tls" name=my-app namespace=default
time="2017-02-09T23:58:12Z" level=info msg="requesting certificate for my-domain.io" context="ingress_tls" name=my-app namespace=default
time="2017-02-09T23:58:12Z" level=debug msg="testing reachablity of http://my-domain.io/.well-known/acme-challenge/_selftest" context=acme domain=my-domain.io
time="2017-02-09T23:58:12Z" level=debug msg="error while authorizing: reachabily test failed: Get http://my-domain.io/.well-known/acme-challenge/_selftest: dial tcp: lookup my-domain.io on 10.3.240.10:53: no such host" context=acme domain=my-domain.io
```

I've followed the examples/gce example. Currently nothing is showing up under load balancers. And my ingress service is not getting an *address*. 
```
| NAME    | HOSTS       | ADDRESS |  PORTS   | AGE |
| my-app | my-domain.io |         |  80, 443 | 8m  |
```
My service and ingress are as follows:

```
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: my-app
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-app
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - my-domain.io
    secretName: default-tls
  rules:
  - host: my-domain.io
    http:
      paths:
      - path: /
        backend:
          serviceName: my-app
          servicePort: 80
      - path: /*
        backend:
          serviceName: my-app
          servicePort: 80
```
